### ISSUE TITLE
Unable to reset _character for docker_agent

### ISSUE THREAD

**Issue by JACKHAHA363** [MultiAgentLearning/playground#101]
In the current code, even though at each round _character is reset by env, but in the docker_agent, there is no corresponding methods. I suggest we add another POST methods which allow env to set the _character of the DockerAgents.

**Comment by cinjon** [comment]
What are you doing that this is necessary?

**Comment by cinjon** [comment]
I'm still confused by this. At the beginning of the game you get your initial position. Are you doing something for which that's too late?

**Comment by JACKHAHA363** [comment]
So the problem is for `docker_agent`, once after the docker is run, then `agent.initial_position` is fixed inside the docker. Then `agent.set_initial_position` method doesn't modify the `initial_position` inside the docker agent.

**Comment by cinjon** [comment]
I'm still confused by this. Are you using docker agent in your regular training runs? What practical operation are you doing that's bumping into this friction?

**Comment by JACKHAHA363** [comment]
Let me give a code example.
```
docker_agent = DockerAgent(container, port)
agent_list = [ RandomAgent() for _ in range(3) ] + [docker_agent]
env = make(config_id, agent_list)
env.reset()
env.act()
```
Suppose in my container `run.py` has run an instance of `MyAgent`, and `MyAgent.act()` need `self.start_position`. Then `env.act()` would return `no start_position error`. The reason is that although `env.reset` set the start_position of `docker_agent`, it doesn't change whatever is inside the container. After the first line, the container is already launched in a sparate thread.

**Comment by cinjon** [comment]
What about getting the start position from the first observation? Is that too late?

**Comment by cinjon** [comment]
I am goign to close this. Reopen if you think it's imperative to get the start position before the first obs.
