### ISSUE TITLE
Read The Docs for more visible documentation

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#105]
I have seen this for a few projects recently. It is a neat way to have documentation a little more visible. Pixelylon from discord suggested it and I think it is a great idea.

https://readthedocs.io

Thoughts?

**Comment by cinjon** [comment]
Yes, these are good additions. What's the work necessary to integrate?

**Comment by weseldridge** [comment]
It seems simple enough. We need an account with "read the docs".  Then a little configuration.

```
MkDocs
When you choose Mkdocs as your Documentation Type, we will first look for a mkdocs.yml file in the root of your repository. If we don’t find one, we will generate one for you.

Then MkDocs will build any files with a .md extension. As MkDocs doesn’t support automatic PDF generation, Read the Docs cannot create a PDF version of your documentation with the Mkdocs option.
```

**Comment by weseldridge** [comment]
Ok. This should be good to go. I haven't tried to push them yet.

https://github.com/weseldridge/playground/commit/89a669efe457c130663c73afbd3f529e15120c2d

The doc page will be https://pommerman.readthedocs.io

I just set it up under my rebellious account. We can move it later if needed.

**Comment by weseldridge** [comment]
https://github.com/MultiAgentLearning/playground/pull/122

**Comment by cinjon** [comment]
PR accepted. Want to try pushing them out now?
