### ISSUE TITLE
Documentation Expansion 

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#106]
With a bunch of new folks and some of the issues we came across with the first competition, I think we need to work on expanding the documentation again. 

## Topic Areas

- [ ] Docker (wrapping your app up)
- [ ] Agent Submission
- [ ] Prep for submission
- [ ] More info on each env (request from discord)
- [ ] Sumbission Requirments - Do you need to present/attendee of NIPS inorder to compet?

**Comment by cinjon** [comment]
Let's add to this:
1. Linting (with yapify --style google)
2. Docstrings (push out what you've changed pls!)
3. ReadTheDocs

Anything else?

**Comment by inoryy** [comment]
From a newcomer perspective the documentation I'm missing most is clear description of the rules for various edge cases, e.g. 

* two bombers moving to same cell
* bomber moves to same cell bomb is kicked to
* where does explosion line end (is it always max range or stops at first target)
* chained explosions

I've eventually figured these out by looking through source code, but would've preferred clear docs.

**Comment by cinjon** [comment]
I think that these are done. Closing unless notified otherwise.
