### ISSUE TITLE
problem in simple_agent.py

### ISSUE THREAD

**Issue by bionick87** [MultiAgentLearning/playground#107]
When I will try to run simple_ffa_run.py I had this error:  

  File "/Users/nicolosavioli/anaconda/lib/python2.7/site-packages/pommerman-0.2.0-py2.7.egg/pommerman/agents/simple_agent.py", line 18, in __init__
    super(SimpleAgent, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj
192:examples nicolosavioli$ python simple_ffa_run.py 

SOLUTION: Search all BaseAgent and change it in BaseAgent(object)

**Comment by cinjon** [comment]
Thanks. Do you mind issuing a PR?

**Comment by pathway** [comment]
I found this bug disappears with python 3.

**Comment by cinjon** [comment]
Great, closing for now then.
