### ISSUE TITLE
occasional zero rewards in pommerman team competition envt

### ISSUE THREAD

**Issue by agakshat** [MultiAgentLearning/playground#109]
As title says, I'm occasionally getting zero rewards for all agents in the TeamCompetition environment - what condition leads to that? as far as I know, a victory leads to +1, loss leads to -1 and ties lead to -1 for all agents.

**Comment by cinjon** [comment]
It's right here in the rewards --> https://github.com/MultiAgentLearning/playground/blob/master/pommerman/forward_model.py#L621

It happens when the game has not ended yet (and consequently it's frequent).
