### ISSUE TITLE
Partial observations in team mode?

### ISSUE THREAD

**Issue by alekseynp** [MultiAgentLearning/playground#114]
Should `team_v0_env` and `team_v0_fast_env` in  `pommerman/configs.py` have `'agent_view_size': constants.AGENT_VIEW_SIZE,` in their `env_kwargs`? It is my understanding from what I've read that the team competition will have partial observations, but there's a decent chance that I misunderstand.

**Comment by cinjon** [comment]
That env was designed for team games with full observation but random teammates. If you look a bit above, `team_competition_env`, has the setup that I think you're looking for.
