### ISSUE TITLE
Player agent that pauses for input

### ISSUE THREAD

**Issue by alekseynp** [MultiAgentLearning/playground#115]
When playing as an arrows or wasd player, the real-time gameplay is pretty good. I can see in the `player_agent.py` that some effort was required to achieve this. I would like to record some high quality human game-play where I really get a chance to consider my next move. I imagine some sort of `player_agent_wait.py` that waits for a valid keypress in `act`.

Would probably then want to implement a button for the `0` action `Stop`.

I'm not sure if there would be any complexity around held buttons. I would hope that in this mode the user would not generally deliberately hold keys, so there might be the opposite problem from what is solved today. That is, today the code has to be careful to make held keys deliver repeated actions, whereas in this situation we probably want to ignore held keys and treat them as a single press event in order to avoid delivering unwanted repeated actions.

Does this seem reasonable?

**Comment by cinjon** [comment]
Looping in @lucasb-eyer as he may have some good input (given that he built the player agent).

Your proposal does seem reasonable, and I like the intent. However, given the complexity of the interaction with held keys, perhaps we should make a separate player agent for this purpose? Otherwise, won't it have to obviate the repeated interaction?

**Comment by alekseynp** [comment]
Yes, I agree it should be an additional player agent.
I'll see if I can implement a `class PlayerAgentWait` in a new `player_agent_wait.py`.

**Comment by cinjon** [comment]
@alekseynp, any update?

**Comment by alekseynp** [comment]
Here's a working commit that I am using at the moment:
https://github.com/alekseynp/playground/commit/a89f560758ffab16b11b7c90a9d509ab9192e44b

I need some more experience with it before I think it's right.

**Comment by cinjon** [comment]
Got it. I'll keep this open for now. Let us know when you have progress.

**Comment by pathway** [comment]
I wrote a blocking player from scratch @alekseynp 

```
import click
# pip install click

class PlayerAgentBlocking(BaseAgent):
    """Block for keyboard input."""

    def __init__(self, character=characters.Bomber, agent_control='arrows'):
        super(PlayerAgentBlocking, self).__init__(character)

    def act(self, obs, action_space):
        key = click.getchar()
        #print(key,repr(key))
        if key=='\x1b[C': return constants.Action.Right.value
        if key=='\x1b[D': return constants.Action.Left.value
        if key=='\x1b[A': return constants.Action.Up.value
        if key=='\x1b[B': return constants.Action.Down.value
        if key==' ': return constants.Action.Bomb.value
        return constants.Action.Stop.value
```

**Comment by cinjon** [comment]
Any update @alekseynp / @pathway?

**Comment by pathway** [comment]
My code above needs to be turned into a PR (with "click" in requirements).  
Im not setup to submit that just now, hopefully soon!

**Comment by pathway** [comment]
PR finally in effect folks: https://github.com/MultiAgentLearning/playground/pull/206

**Comment by pathway** [comment]
I think this can be closed as of https://github.com/MultiAgentLearning/playground/commit/3ccc94e13dd4e3a02d1c4e283064d89e45620818

**Comment by cinjon** [comment]
yup, tahnks!
