### ISSUE TITLE
V1 environment wall collapse steps exceed number of rings

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#118]
On an 11x11 board collapsing ring 0-3 should be all that is needed to force at most one surviving agent.
Currently the number of collapsing rings is set to the board size and as such the number of steps between collapses is unnecessarily small.

**Comment by cinjon** [comment]
Good call. I agree. Mind issuing a PR?

**Comment by cinjon** [comment]
Addressed in latest commit.

**Comment by cinjon** [comment]
(this one --> https://github.com/MultiAgentLearning/playground/commit/5cb40369313f627b45690ef0bd84ad6d4a241ffc)
