### ISSUE TITLE
Include running environment  (and maybe additional environment data) in agent observations 

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#119]
Agents for NIPS 2018 competition are initially placed in a V0 environment. However when team tie twice in a game all subsequent games are played in a V1 (collapsing wall) environment until one team wins,

Currently the agent has no knowledge of the environment type (V0/V1) or in the case of V1 no knowledge about the collapse schedule.

An alternative to including it in the observations would be to add parameters to agent initialization or allow specialized agents per environment.

**Comment by cinjon** [comment]
I think the easiest thing is to just include it in the observation. The agent already gets the step, so these two pieces of information are sufficient.

**Comment by weseldridge** [comment]
Ok. I was able to get the game type into the agent's obs. 

```
 'game_type': 'FFA',
```

I didn't see a way to get the current env value into it though. This might be my inexperience in python though...

There is a PR for the current game type. Any suggestions?

**Comment by cinjon** [comment]
I added a comment to the PR. I think you want 'value' instead of 'name'.

**Comment by weseldridge** [comment]
What about getting the env it is running in. Like v0, v1, v2?

**Comment by cinjon** [comment]
Oh, my bad, that's right we want that information and not the game type. 
Hmm, I don't think there is a clean solution with the current setup. Might be that the best approach is to add 'env_entry_module': <str entry module, e.g. 'pommerman.envs.v0'> to the dict here https://github.com/MultiAgentLearning/playground/blob/939921e7d7e70fe9715a9f1c5d3ed472a40d2758/pommerman/configs.py#L73

**Comment by weseldridge** [comment]
Perfect. I will get that in sometime today. I might have to do it on my flight though.

**Comment by cinjon** [comment]
Addressed in #120
