### ISSUE TITLE
Add actions, failed actions, and collisions to saved game state.

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#123]
This is a request that came in through Discord from @suphoff.

**Comment by suphoff** [comment]
@cinjon - Don't have any code (and very happy not to have to write any) - was just planning ahead to prevent pipeline stalls.

**Comment by suphoff** [comment]
@cinjon : Any chance you can cherry pick those changes from your research branch?
Do you also have code to compare two states (for #108 )?

**Comment by cinjon** [comment]
I'm actually a little confused now. Is it the case that in totality you just want the actions recorded along with the game state?

**Comment by cinjon** [comment]
And what do you mean wrt code to compare two states? Is a "state" here the info in a game state file?

**Comment by suphoff** [comment]
State as in:
-  S(t+1) = forward.model.step ( S(t) x A(t) ) .... well the current recording of the states in json.

My main reason is that just recording all the states S(0) .. S(T) does not really describe what actually happened in a game. (Example: Agent A actively colliding with Agent B to prevent a move in contrast to both Agents just not moving).  ( For a given states S(t), S(t+1)  the set of Actions A(t) : S(t+1) = forward.model.step ( S(t) x A(t) ) may have multiple members ).

The recorded action could be used for improving visualization of a recorded game (showing collisions, failed kicks ...) using an enhanced step function or actions could just be displayed (as arrows) in a state transition animation.

It could also be used to replay a game with a new or changed step functions and verify that the resulting states are as expected. (A nice and easy code regression test)

**Comment by cinjon** [comment]
Ok, so just to clarify, would it be sufficient to additionally record the
action requested at every step by each agent? We could additionally record
the action actually taken.

**Comment by suphoff** [comment]
I believe the action requested is all that is needed.

( If anyone really needs the action taken it can be easily extracted from state changes (unless the agent is dead in the next state) or calculated from start state and requested actions)

**Comment by cinjon** [comment]
We discussed this offline. I will edit it to add in the action to the game
state saving.

**Comment by cinjon** [comment]
https://github.com/MultiAgentLearning/playground/commit/0017eef3e0c137c329f50bf048be289ca691260d should handle the issue by including an "intended_actions" in the json. Let me know if this is insufficient.

**Comment by suphoff** [comment]
It is sufficient - however would it not be nicer to group S(T) with A(T) instead of S(T+1) with A(T) ?

**Comment by suphoff** [comment]
On second thought - for human players we definitely need to render before asking for actions.
So unless save_json is split out from render in the environment we can only report the previous actions.
... and actions can be reordered anyway as part of processing the game file without changes in the env api.
@cinjon : Happy with the current solution.
