### ISSUE TITLE
Error when running example CLI command.

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#124]
@ GRomera

Got this an error when running the example player. This is the example command.

```
pom_battle --agents=player::arrows,test::agents.SimpleAgent,random::null,random:null --config=PommeFFACompetition-v0
```
 This is the error.
![errors](https://user-images.githubusercontent.com/138982/43554271-1835b41a-95b9-11e8-8226-bd3e02bbd7cd.PNG)

**Comment by cinjon** [comment]
The command is missing a `:` in `random:null` at the end. Do a git pull, add that in, and you're good to go.
