### ISSUE TITLE
Link in README.md to CONTRIBUTING.md does not direct; 404 error

### ISSUE THREAD

**Issue by kylebegovich** [MultiAgentLearning/playground#125]
When clicking the link in the README, you are not redirected to the correct, Contributing document. Instead, you are directed to a 404 page. See underlined Contributinr link:

<img width="1361" alt="screen shot 2018-08-02 at 2 02 24 pm" src="https://user-images.githubusercontent.com/21372311/43604999-bea44ae8-965c-11e8-9a81-57f014824b5f.png">
Redirects to:
<img width="1361" alt="screen shot 2018-08-02 at 2 02 37 pm" src="https://user-images.githubusercontent.com/21372311/43605000-bebac7dc-965c-11e8-8805-21e8e5f58e80.png">

**Comment by cinjon** [comment]
addressed in #126
