### ISSUE TITLE
agent ammunition limit does not account for layed but unexploded bombs.

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#127]
Currently just a zero priority issue to fix if anyone works in the general area. 
(no impact on game play with standard environments )

Picking up an extra bomb fails if self.ammo is already 10 (or higher)
  if item == constants.Item.ExtraBomb:
            self.ammo = min(self.ammo + 1, 10)

However dropping a bomb with ammo == 10 would decrease  ammo to 9 and allow an extra bomb to be picked up - to restore ammo to 10. Once the bomb explode ammo would increase to 11.
Picking up an extra bomb would then actually decrease ammo back to 10.

**Comment by cinjon** [comment]
Yeh that's a bug we should fix before the competition. You're right though that it's not at the very top of the agenda.

**Comment by cinjon** [comment]
Addressed in https://github.com/MultiAgentLearning/playground/commit/6c262dc1983fdffe6edfd2a55be63f8f7e6c1afc. Thanks @suphoff.
