### ISSUE TITLE
`ffa_v0_env` in jupyter notebook should be replaced by `ffa_v0_fast_env`

### ISSUE THREAD

**Issue by xysun** [MultiAgentLearning/playground#128]
I suspect the notebook is simply not up to date. I tested replacing all `ffa_v0_env` and was able to run the whole notebook. 

(I also hesitated to do a PR because commit on notebooks are usually messy with unwanted local env changes, eg. cell execution number, etc; however if a PR is ok please let me know I'm more than happy to do it)

[This](https://github.com/MultiAgentLearning/playground/blob/master/pommerman/configs.py#L82) is the definition in pommerman/configs.py

Thanks.

**Comment by cinjon** [comment]
Hey there, a PR is definitely ok and appreciated! Thanks for finding this.

**Comment by xysun** [comment]
Thanks @cinjon . PR submitted #129
