### ISSUE TITLE
Contributor Docs

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#13]
I have started working on a couple contributor documents. One is a code of conduct. For the most part, it is copied from openai gym. There is also a small contributor guide. I just pulled parts from different projects.

https://github.com/weseldridge/playground/blob/contributor-docs/CONTRIBUTING.md

https://github.com/weseldridge/playground/blob/contributor-docs/CODE_OF_CONDUCT.md

What are y'all thoughts?

**Comment by cinjon** [comment]
Appreciated for sure!

**Comment by weseldridge** [comment]
@cinjon Any updates you want for this PR?

**Comment by weseldridge** [comment]
Ok. I pushed some updates. Also added a section linking to the code of conduct in the contributor guide. There wasn't any place referring to it.

I also added a response to the '.src/' in the `.gitignore` file. I am getting that dir when running pip outside of a container. Thoughts. I am not sure what is in the docker build process, but I wouldn't think it would affect it. Just didn't want to comment a full dep.

**Comment by weseldridge** [comment]
I removed the entry from the `.gitignore` file.

**Comment by cinjon** [comment]
Ohhhh, ok, so it was relevant just to your build. 

I am not getting that in my setup, and now that you bring it up, I think that's a good idea so that future contributors don't accidentally add their docker builds. Sorry about the confusion!

**Comment by cinjon** [comment]
I'll accept this anyways, and you can add that into the gitignore as you wish.
