### ISSUE TITLE
Error when launching a json customized board

### ISSUE THREAD

**Issue by GRomera** [MultiAgentLearning/playground#130]
When trying to run a customized board by a json file in the CLI, the following command :
`$ pom_battle --agents=player::arrows,test::agents.SimpleAgent,random::null,random::null --config=PommeFFACompetition-v0 --render --game_state_file=c:/Users/grome/venv/Lib/site-packages/pommerman/cli/gameboard.json`
Will throw this error : 
![eror](https://user-images.githubusercontent.com/26470347/43916852-bc8d8cda-9bdc-11e8-92eb-10e86fd23c8b.PNG)

Note that commands removing the `test::agents.SimpleAgent` argument works just fine : 
`$ pom_battle --agents=player::arrows,random::null,random::null,random::null --config=PommeFFACompetition-v0 --render --game_state_file=c:/Users/grome/venv/Lib/site-packages/pommerman/cli/gameboard.json`

A way to solve that issue is to change the line : https://github.com/MultiAgentLearning/playground/blob/master/pommerman/agents/simple_agent.py#L375 (`while prev[next_position] != my_position:`)

To : ` while prev[next_position] !=None and prev[next_position]!= my_position:  `

**Comment by cinjon** [comment]
Hmm, interesting. Is this happening before taking any steps (i.e. is it occurring from the new initial game state itself) or is it some time after the game loads?

**Comment by GRomera** [comment]
So the game loads like it should, but a second later (maybe less) the game closes itself. You can see the json file has been read properly but nothing else

**Comment by cinjon** [comment]
In the meantime, has the game taken any steps or is it crashing on that one step? 
Can you post your initial game state file? 
How did you generate it?
Are you sure that it's loading correctly?

**Comment by GRomera** [comment]
It seems like it reads some steps, since its properly reading the board file but I do believe it fails when placing the agents onto the board.

This is the game state file, the credit goes to Wes since he's the one who originally made it.
The only thing I have changed for debugging purposes is the "board:", that has been done to see if the file is being loaded correctly the most obvious way

```
{
    "agents": "[{\"agent_id\": 0, \"is_alive\": true, \"position\": [2, 1], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 1, \"is_alive\": true, \"position\": [11, 2], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 2, \"is_alive\": true, \"position\": [10, 11], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 3, \"is_alive\": true, \"position\": [1, 11], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}]",
    "board": "[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0], [0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0], [0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]",
    "board_size": "13",
    "bombs": "[]",
    "flames": "[]",
    "items": "[[[12, 4], 8], [[8, 1], 9], [[7, 11], 6], [[1, 4], 8], [[6, 2], 6], [[5, 2], 8], [[12, 5], 9], [[11, 7], 7], [[4, 11], 8], [[9, 10], 6], [[1, 6], 8], [[5, 11], 8], [[7, 8], 6], [[8, 7], 7], [[10, 4], 7], [[6, 11], 8], [[11, 4], 8], [[5, 8], 7], [[2, 12], 9], [[12, 2], 7], [[11, 6], 9], [[5, 3], 7], [[3, 5], 9], [[7, 1], 8], [[5, 1], 6]]",
    "step_count": "1"
}
```

**Comment by cinjon** [comment]
Can you verify if it actually takes multiple steps please?

**Comment by GRomera** [comment]
How can I verify it properly?

**Comment by cinjon** [comment]
The easiest by far is to just print out the results of each step. If there is no print out, then it isn't stepping. If there are multiple, then something is happening further downstream.

**Comment by weseldridge** [comment]
@GRomera this is done by passing in the `--record_json_dir=/path/to/path` option in the cli.

**Comment by GRomera** [comment]
@cinjon @weseldridge  So I passed that argument and this is the only result I get when I run the game 
```
{
    "agents": "[{\"agent_id\": 0, \"is_alive\": true, \"position\": [2, 1], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 1, \"is_alive\": true, \"position\": [11, 2], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 2, \"is_alive\": true, \"position\": [10, 11], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}, {\"agent_id\": 3, \"is_alive\": true, \"position\": [1, 11], \"ammo\": 1, \"blast_strength\": 3, \"can_kick\": false}]",
    "board": "[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 0], [0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 13, 0], [0, 0, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]",
    "board_size": "13",
    "bombs": "[]",
    "flames": "[]",
    "items": "[[[12, 4], 8], [[8, 1], 9], [[7, 11], 6], [[1, 4], 8], [[6, 2], 6], [[5, 2], 8], [[12, 5], 9], [[11, 7], 7], [[4, 11], 8], [[9, 10], 6], [[1, 6], 8], [[5, 11], 8], [[7, 8], 6], [[8, 7], 7], [[10, 4], 7], [[6, 11], 8], [[11, 4], 8], [[5, 8], 7], [[2, 12], 9], [[12, 2], 7], [[11, 6], 9], [[5, 3], 7], [[3, 5], 9], [[7, 1], 8], [[5, 1], 6]]",
    "step_count": "1"
}
```

**Comment by cinjon** [comment]
Sorry, I was delinquent on this as it coincided with an extended trip. @GRomera is this still an issue for you?

**Comment by PixelyIon** [comment]
@GRomera @cinjon I ran into this error aswell. I think it was due to the position not being loaded in as a tuple.

**Comment by GRomera** [comment]
@cinjon Not anymore I managed to fix it, but thanks for the follow up
