### ISSUE TITLE
Fix simple agent's _djikstra implementation

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#138]
Fix _djikstra  implementation - it is written as if the priority queue would automatically update priorities.

As the distance between neighbors in this graph is always one just use a simple queue and push any nodes with reduced distance at end of queue.

**Comment by weseldridge** [comment]
Dude, you're awesome!

**Comment by weseldridge** [comment]
Amazing. That was so fast. 🏃‍♂️
