### ISSUE TITLE
Canadian graphics for NIPS

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#142]
Stephan messaged me a really neat idea. Just wanted to put it here to get feedback and ideas.

You should make a Canada rendering option:
Rigid walls are ice
Wood walls are snow drifts
Can kick item is a hockey stick
The bomb is hockey puck shaped :smiley:
All agents wear winter hats :smiley:

**Comment by PixelyIon** [comment]
Great idea! I was thinking if we could do this + do a more minimalistic style more akin to 2048 and we'd get a nice looking renderer.

**Comment by cinjon** [comment]
Hehe, community contributed skins would be 👍 , albeit I think the one that you did already is phenomenal ;).
