### ISSUE TITLE
(Bug) SimpleAgent - Bombs itself on the 1st move

### ISSUE THREAD

**Issue by PixelyIon** [MultiAgentLearning/playground#144]
This behavior is extremely common when I'm collecting data from a vast variety of matches. However I cannot produce data of it due to saving in an unconventional format.

**Comment by suphoff** [comment]
_directions_in_range_of_bomb looks sketchy

**Comment by cinjon** [comment]
What is the format that would be helpful for debugging this? Definitely interested in solving these kinds of concerns.

**Comment by suphoff** [comment]
My working theory is that SimpleAgent regard the direction away from a bomb as a safe direction - then can't go far enough away from the bomb and backs itself into a dead end still in range of the bomb. Would just use Dijkstra's for bomb avoidance  ...

**Comment by PixelyIon** [comment]
> 
> 
> What is the format that would be helpful for debugging this? Definitely interested in solving these kinds of concerns.

Write a while loop or something of the sort to run matches till it finds one that ends in less than 20 steps (A bit of leeway, just in case) and save that match as JSON. That should be enough to reproduce the bug.

**Comment by PixelyIon** [comment]
Refer to #169 for further discussion.
