### ISSUE TITLE
Friendly games over discord

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#145]
Remotely playing chess has a long history.
Players agree to a start state (who is starting) - and then exchange move information.
Every player applies information about the remote players to their own board.

Pommerman could be played in the same way using discord as a message channel by:

1. A start player (SP) messages a game invite for a specific game type to a group or private discord channel
2. Player(s) (P(n))  accepting the game invitation and posting acceptance message
3. The start player (SP) selecting a subset of players that posted  acceptance message and sending a GAME START message containing a random seed describing the board and the roles (position) of each player.
4. All players generate environments using random seed from the start message and start agents for their local agents and for remote discord agents.
5. Players will broadcast the actions (up, down, ..) of their local agents (along with current game id, step , ..) to discord for all other players to pick up.
6. Player steps environment once all local and remote actions.
7. Loop 6,7 until game is over - SP posts results

**Comment by cinjon** [comment]
Hehe. As all good games eventually do, we are now well on our way to making a MUD. :)
