### ISSUE TITLE
You will not be able to render --> Library "GL" not found

### ISSUE THREAD

**Issue by phoenixbai** [MultiAgentLearning/playground#146]
I tried to run pommerman in docker, and it failed as below:
`
(anaconda3) phoenix@phoenixbai:docker-agent$ docker run pommerman/simple-agent
 * Running on http://0.0.0.0:10080/ (Press CTRL+C to quit)
^CImport error GL! You will not be able to render --> Library "GL" not found.
`
python version: Python 3.6.5 :: Anaconda, Inc.

in non docker mode, it works fine.
what could be the possible cause? how can I fix it?

thanks

**Comment by cinjon** [comment]
Are you trying to render? Unless you do some heavy plumbing, you won't be able to render in the Docker env and this error seems about right for that.
