### ISSUE TITLE
v1 (collapsing board) - bombs caught by the collapse are not returned to agent

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#147]
When a bomb is removed from the board because of the board collapse the ammo value of the bomber (agent) of the bomb is not increased.

Oversight or planned?

**Comment by weseldridge** [comment]
I think that is correct. You should not get a bomb back if it falls off the board. You have already laid it, and therefore used it.

Your thoughts on this?

**Comment by cinjon** [comment]
Oversight. I'll fix it this weekend batched with other backlog. Thanks for catching it @suphoff

**Comment by weseldridge** [comment]
Yeah. I was thinking of if you want more than one bomb... but if you only have one and laid it you def want to get a new one.

That previous statement was b/c I hadn't had coffee yet. 😬

**Comment by cinjon** [comment]
Ack, see https://github.com/MultiAgentLearning/playground/commit/ceec7c70fb933528b8f7815d5faca7787c8cc715. Thanks!
