### ISSUE TITLE
Restricted seed range in run_battle.

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#148]
run_battle.py: 

if seed is None:
        seed = random.randint(0, 1e6)

I can easily compress 1e6 game start states into < 16MB and fingerprint them with the observable parts to narrow down probability distribution of hidden items.

Please remove the temptation to do so :-) 
( And pick random seeds spanning 2^32 for NIPS ..)

**Comment by cinjon** [comment]
Done, see https://github.com/MultiAgentLearning/playground/commit/bb2b2327a91be84e45d359f86c82a3c69f4541d8. Thanks!
