### ISSUE TITLE
Better segmentation of Teams

### ISSUE THREAD

**Issue by PixelyIon** [MultiAgentLearning/playground#158]
Currently it isn't the easiest to track which team is which as the players are colored the same as they are in FFA. If we could add some sort of tint or even other sprites for players in either team it would be much easy to visually parse the information.

**Comment by weseldridge** [comment]
Maybe they have the same color helmet?

**Comment by PixelyIon** [comment]
@weseldridge I like the second one but in it's style but I don't think the colors match that well with the rest of the color scheme.

**Comment by weseldridge** [comment]
@PixelyIon and @suphoff  this is in a PR now. I ended up going with up's suggestion.

![screen shot 2018-10-29 at 13 30 00 pm](https://user-images.githubusercontent.com/138982/47673080-990f9700-db81-11e8-8c3b-3e4b3cbedbe3.png)

**Comment by suphoff** [comment]
@cinjon : Why are you closing the issue so early?
 render_dead_alive() still needs to be adjusted to show the new team icons :smiley:
