### ISSUE TITLE
starter guide

### ISSUE THREAD

**Issue by Scitator** [MultiAgentLearning/playground#160]
Hi,

Do you have any starter guide for newcomers? LIke full pipeline for training and submitting basic agent?

Thanks!

**Comment by weseldridge** [comment]
We do not have one. I would start with the notebook.

https://github.com/MultiAgentLearning/playground/blob/master/notebooks/Playground.ipynb

All of the docs are also on read the docs. there are some links to the code that I need to fix though.

https://pommerman.readthedocs.io/en/latest/

I would also look at 

https://github.com/MultiAgentLearning/playground/blob/master/pommerman/agents/tensorforce_agent.py

I have an example I was going to make a video around but haven't gotten to it yet. The code is a bit of a mess. Sorry. 😬

https://github.com/weseldridge/playground/blob/agent_traning/agent/tensorforce_agent.py

As you get into if you have feedback please let us know.

**Comment by cinjon** [comment]
There's also the Discord channel. People have had great success getting up to speed via asking questions there.
