### ISSUE TITLE
Collecting Information

### ISSUE THREAD

**Issue by GRomera** [MultiAgentLearning/playground#161]
Would it be possible to add/record on a single JSON file the following things?:

-Bombs Laid
-Blocks Destroyed
-Power ups collected ( By a human player)
-Steps  Taken
-Agents (non-human) killed

**Comment by PixelyIon** [comment]
You should be able to collect this data using the env's observation. Once your done with that use python's inbuild `json` module (https://docs.python.org/3/library/json.html) to encode all the data into JSON.

**Comment by PixelyIon** [comment]
For collection of data these are some of the privates that the env has they might help you: https://github.com/MultiAgentLearning/playground/blob/master/pommerman/envs/v0.py#L40.

**Comment by PixelyIon** [comment]
@GRomera @cinjon Stale issue. Recommended to close it.
