### ISSUE TITLE
FYI: Unexpected collapsing wall/fire interaction in V1 environment 

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#164]
Collapsing walls in the V1 environment build onto a fire will disappear and be replaced by fire or passage (if fire is about to be extinguished).

**Comment by suphoff** [comment]
A bomb sharing a square with an agent will also survive a collapsing wall.

_collapse_board() should really be called before the v0 step() function to ensure observations are consistent with state.

**Comment by cinjon** [comment]
Aye, thanks for adding that on. I'm a bit backed up right now and will get to this after next week.

**Comment by cinjon** [comment]
Was this entirely addressed in #175 ? We didn't just collapse the bombs there, but the items as well.

**Comment by suphoff** [comment]
Looks like the fix for #175 does not remove the flames. (And when they go out they will cause passages)
