### ISSUE TITLE
Game state snaphot

### ISSUE THREAD

**Issue by mplantady** [MultiAgentLearning/playground#18]
Here is a suggestion to improve testing/debug of agent behavior in specific cases: a game snapshot could allow to start a battle at a specific step with all configuration restored: Agent & bomb positions, board topology, bonus ...

A snapshot could be created :
- Using a HotKey to save a game in progress
- Manually by editing a file

Using a human-readable format for this snapshot (json/xml) would allow us to edit the configuration to test different edge-cases.

To start a game with a snapshot, an optional file-path parameter could be added to _run_battle.py_

**Comment by cinjon** [comment]
I added a branch that starts this here: https://github.com/MultiAgentLearning/playground/tree/gamestate.
Feel free to finish what I started there.

**Comment by cinjon** [comment]
This is done. Thanks @mplantady
