### ISSUE TITLE
Erroneous encoding of walls in 'board' array in documentation

### ISSUE THREAD

**Issue by shivam-agarwal** [MultiAgentLearning/playground#196]
There is an error in the documentation of wooden and rigid walls of 'board' array in environment.md file.
As seen from the json data and images, a wooden wall is encoded as value 1 and rigid wall as value 2. Currently, in the documentation, their values are reversed.

See an example below with game state and corresponding image:

"agents": "[{\"agent_id\": 0, \"is_alive\": true, \"position\": [1, 1], \"ammo\": 1, \"blast_strength\": 2, \"can_kick\": false}, {\"agent_id\": 1, \"is_alive\": true, \"position\": [9, 1], \"ammo\": 1, \"blast_strength\": 2, \"can_kick\": false}, {\"agent_id\": 2, \"is_alive\": true, \"position\": [9, 9], \"ammo\": 1, \"blast_strength\": 2, \"can_kick\": false}, {\"agent_id\": 3, \"is_alive\": true, \"position\": [1, 9], \"ammo\": 1, \"blast_strength\": 2, \"can_kick\": false}]",
"board": "[ **[0, 0, 1, 2, 2, 0, 1, 1, 1, 2, 1]**, [0, 10, 0, 0, 2, 2, 2, 0, 0, 13, 1], [1, 0, 0, 1, 2, 0, 0, 1, 1, 0, 1], [2, 0, 1, 0, 2, 2, 1, 1, 2, 0, 0], [2, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1], [0, 2, 0, 2, 1, 0, 1, 0, 2, 2, 2], [1, 2, 0, 1, 0, 1, 0, 1, 2, 2, 1], [1, 0, 1, 1, 2, 0, 1, 0, 1, 0, 0], [1, 0, 1, 2, 2, 2, 2, 1, 0, 0, 0], [2, 11, 0, 0, 2, 2, 2, 0, 0, 12, 0], [1, 1, 1, 0, 1, 2, 1, 0, 0, 0, 0]]",
"board_size": "11",
"bombs": "[]",
"flames": "[]",
"intended_actions": "[]",
"step_count": "0"
![image](https://user-images.githubusercontent.com/5621665/51548826-6e279d00-1e69-11e9-8185-96fc4becbe71.png)

**Comment by cinjon** [comment]
This was addressed in the update. Thanks!
