### ISSUE TITLE
Bomb Lifetime is faulty

### ISSUE THREAD

**Issue by m2q** [MultiAgentLearning/playground#198]
After a player plants a bomb, the bomb gets ticked in the same step! 

That means a bomb with lifetime 1 will explode immediately in the step where it's been planted.  An easy fix would be to just set the bomb lifetime after planting a bomb to BOMB_LIFETIME + 1.

It would also be possible to put the bomb calculation at the start of the step method, however that complicates the bomb kicking movements a lot. I think the former solution is fine

**Comment by cinjon** [comment]
This is reasonable to me. Thanks for bringing it to our attention. Adjusted in 9e4d78f.

**Comment by cinjon** [comment]
Heads up @m2q that this change causes agents from the prior competitions to not be as good because they were built with a different setup. We'd like to maintain their efficacy for the next competition, and so I think a reasonable middle ground is to additionally change DEFAULT_BOMB_LIFE to be 9.
