### ISSUE TITLE
docker agents running issue

### ISSUE THREAD

**Issue by CreamyLong** [MultiAgentLearning/playground#201]
ConnectionError:  HTTPConnectionPool(host='localhost', port=10080): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000235FFD791D0>: Failed to establish a new connection: [WinError 10061] Unable to connect because the target computer actively refused.',))

And I do not know how to use docker agent in the game, how could I change simple docker agent to the different docker agent, where can I see the information of different docker agent.

**Comment by d2hf** [comment]
Did you figure it out? I am having the same issue here...

**Comment by cinjon** [comment]
This is probably related to the timeout. Increase the timeout and try again.
