### ISSUE TITLE
Need admin/'root' permissions/privileges to install pommerman

### ISSUE THREAD

**Issue by maym2104** [MultiAgentLearning/playground#203]
It appears that we need admin privilege on Windows and equivalents on Linux systems to install pommerman with:
``pip install .``
even though we are installing in a virtual environment or a conda environment. 

It is not a problem on my own machine, but on clusters where I do not have such privileges, I cannot install using the command above. A workaround is
``python setup.py install``
but I need to uninstall pommerman before reinstalling to update the env version with my changes, because otherwise, it won't update.

**Comment by activatedgeek** [comment]
@maym2104 I just did a fresh install in a new environment and did not come across this permissions issue. Can you give a full trace of the error? Including steps that led you to this?

**Comment by maym2104** [comment]
Ok turns out I could not reproduce it on Windows but could on the cluster (CentOS). 
![image](https://user-images.githubusercontent.com/7849866/55595425-b1c44000-5711-11e9-9304-8fb83d8b59bf.png)

Steps:
``virtualenv testenv``
``source testenv/bin/activate``
``git clone https://github.com/MultiAgentLearning/playground``
``cd playground``
``pip install -U .``

If I can reproduce it on Windows or on local Ubuntu I will let you know but it might be an issue of the cluster server only... I already contacted a support guy of the cluster but he could not reproduce it.

**Comment by maym2104** [comment]
Ok I could install it when I clone it directly in my home space... Must be the permissions of the specific space (scratch) I was using. Thank you for your help and sorry to have bothering you guys about that.
