### ISSUE TITLE
Fires not extinguished by collapsing wall

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#204]
Looks like the issue was overlooked at the last round of collapsing wall fixes.

Happy to submit a patch once I have my environment up and running again. (for verification)

**Comment by weseldridge** [comment]
I cannot remember what caused this, but in some cases, the playable board isn't removed. I remember seeing that during some of the playbacks in the competition.

**Comment by suphoff** [comment]
@weseldridge : Yeah - you probably observed this then - when the flames finally expire they are replaced by a passage. I tried to use collapsing walls to force a winner for learning - but with this bug agents frequently ended up walled in and isolated apart from each other.

**Comment by weseldridge** [comment]
Yup! That is it.

**Comment by suphoff** [comment]
Fixed by #205
