### ISSUE TITLE
Don't rely on pickles to serialize the game state

### ISSUE THREAD

**Issue by mat7e** [MultiAgentLearning/playground#21]
When communicating with an agent inside a docker container, the `observation` and `action_space` are encoded using Python pickles. This makes it very hard to use anything other than Python for writing agents. Also the original project structure has to be copied to decode the pickles.

Therefore it would be more convenient to encode the game state using JSON only.

**Comment by weseldridge** [comment]
That makes sense. Are you working in a different language now?

**Comment by cinjon** [comment]
Agree! Thanks for catching that. Any chance you’d be up for making the
changes and issuing a PR? It will be difficult for me to get to this until
next weekend.

**Comment by weseldridge** [comment]
Ok. There is a PR for the JSON update.

**Comment by mat7e** [comment]
Thank you @weseldridge for the PR!

I am working with Python now, but also wan't to implement one algorithm with Scala.

**Comment by weseldridge** [comment]
That is awesome! I believe that is the first agent I have heard of (planned/or being built) in a language other than Python. 

Cinjon will be back in the next couple of days, and we will get this PR into master.

**Comment by cinjon** [comment]
addressed in #27

**Comment by cinjon** [comment]
opening this back up because it needs to be adjusted. will do it after #26 is completed.

**Comment by activatedgeek** [comment]
Well it turns out that we are using non-{JSON serializable} classes inside the observation object and hence we can't really do anything except binary serialization for now. I reverted the commit from #27 but there still is an error.

This line is the error in `agent_classes.py`.
```
action = req.json()['action']
```

with the error being
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by cinjon** [comment]
this is working on my end now. successfully ran a docker agent with three other SimpleAgents.
