### ISSUE TITLE
TF agent not compatible with v2 environment.

### ISSUE THREAD

**Issue by dnandha** [MultiAgentLearning/playground#245]
The tensorforce agent is currently not compatible with the v2 environment because of a small mistake:

https://github.com/MultiAgentLearning/playground/blob/4ba44f601157ab04aa0291bed7c2de4bde9e8f6b/pommerman/agents/tensorforce_agent.py#L27

'type' must be changed to string ('int') instead of class type (int).

Because tensorforce/models/distribution_model.py checks for `elif action['type'] == 'int'` and as it is now, this test fails and `self.distributions` stays empty. This leads to a runtime error during a later point, e.g. when calculating `log_probs` for `self.distributions` for the gradients.

**Comment by cinjon** [comment]
Thanks! Do you mind submitting a PR?
