### ISSUE TITLE
Missing obs transformation 'bomb_moving_direction' in docker runner

### ISSUE THREAD

**Issue by dnandha** [MultiAgentLearning/playground#249]
https://github.com/MultiAgentLearning/playground/blob/8c06a21da5758b570b708e9dd3337e1fa1e67e71/pommerman/runner/docker_agent_runner.py#L41

Unlike the other board observations 'bomb_moving_direction' is not converted to a numpy array in the docker runner. If the user treats this observation as all other it leads to the following error during (Docker) runtime:
`TypeError: list indices must be integers or slices, not tuple`

Note that this leads to an error **only** when running with the Docker agent, the same (agent) code will not throw an error when the agent is run directly.

**Comment by cinjon** [comment]
(Thank you! Much appreciated.)
