### ISSUE TITLE
Support for arbitrary number of agents 

### ISSUE THREAD

**Issue by activatedgeek** [MultiAgentLearning/playground#28]
Currently the `ffa_v0` configuration does not support less than four agents (and perhaps arbitrary number). It would be helpful to make it support arbitrary number of agents (or a reasonable range).

**Comment by cinjon** [comment]
Agree. Should support 2-4 agents. Might be easiest to do this with a DummyAgent that initializes as dead.

**Comment by activatedgeek** [comment]
Interesting! That should work for now.

**Comment by lewj85** [comment]
Added DummyAgent (see pull request). Can close this issue.

**Comment by activatedgeek** [comment]
@lewj85 That is awesome. Just add a Fixes #28 in the PR and this issue will close when the PR merges.

**Comment by cinjon** [comment]
Closing this because there is an easy way to do this now (and has been for a while) through initializing the game state as such.
