### ISSUE TITLE
Debugging Docker Agents

### ISSUE THREAD

**Issue by activatedgeek** [MultiAgentLearning/playground#30]
It is kind of hard to debug Docker agents right now if they are erroneous. Looking for ideas here.

This will be helpful while running competitions as well.

**Comment by cinjon** [comment]
I'm finding the same. Changing the log level, using print statements, and then checking the logs has been [un]bearable. I'll look into this.

**Comment by cinjon** [comment]
Closing this for now as it's not a high priority on my end.
