### ISSUE TITLE
Cleanup of (Docker) agents

### ISSUE THREAD

**Issue by activatedgeek** [MultiAgentLearning/playground#31]
While experimentation, it turns out that the docker container keeps running even after the game. This interferes with the next run of the program (either with port conflicts).

The cleanup should probably be with `env.close()` for each environment.

**Comment by cinjon** [comment]
Aye, sounds good. Thanks for tracking this.

**Comment by cinjon** [comment]
Closing this for now as it's not a concern for anyone but ... me :).
