### ISSUE TITLE
Registering all environments with gym

### ISSUE THREAD

**Issue by activatedgeek** [MultiAgentLearning/playground#32]
It will be easier if we can register all environments with gym and then use `gym.make`.

The problem with using `configs` function call is that the static analysis and debugging is obscure currently. The extra arguments for the environments can already be provided via the gym `register` method.

The general flow would look like this

```
env = gym.make('PommeFFA-v0')
env.set_agents(agent_class_list)
```

instead of the runtime evaluation that we do currently. The configurations are static and hence the need for those runtime function calls are now unnecessary when `gym` already provides a way to do that for us. Plus, this way of sending in strings for parsing is brittle because if the class interfaces change, everybody's code breaks. A better idea might be to provide explicit class list. (Of course, if you want an additional CLI like `run_battle.py`, the string parsing logic can happen there)

See #29 for a step in this direction. Comments welcome.

**Comment by cinjon** [comment]
Agree. Thanks for addressing this. Let's get #29 in today.
