### ISSUE TITLE
Problems with import pommerman module in Jupyter Notebook example file

### ISSUE THREAD

**Issue by Yourist** [MultiAgentLearning/playground#36]
Hello!
I cloned the repository to my pc,  created venv, installed all packages, ran script in "Get started". Everything Okay.
But when I try to run jupyter notebook in repo - "No module named "pommerman"".
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-9be4011715df> in <module>()
      3 import numpy as np
      4 
----> 5 from pommerman.agent_classes import RandomAgent, PlayerAgent, Agent
      6 from pommerman.agents import SimpleAgent
      7 from pommerman.configs import ffa_v0

ImportError: No module named 'pommerman'
```
If I copy notebook in the main directory and run it - "No module "pommerman.agent_classes"".
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-9be4011715df> in <module>()
      3 import numpy as np
      4 
----> 5 from pommerman.agent_classes import RandomAgent, PlayerAgent, Agent
      6 from pommerman.agents import SimpleAgent
      7 from pommerman.configs import ffa_v0

ImportError: No module named 'pommerman.agent_classes'
```
When I tried to run it right after cloning repo and activating venv a few weeks ago, there are no problems.
Has anyone encountered such a problem?
Thanks!

**Comment by activatedgeek** [comment]
You need to run
`pip install .` from the root folder of the project and everything should work. 

There is an update to the notebook in PR #35 which updates to the latest APIs. But as a quick fix, change line 5 to `from pommerman.agents` instead of `pommerman.agent_classes`.

**Comment by Yourist** [comment]
@activatedgeek Thank you!
I did it. 
And have another problem:
It works only after copying notebook file in the main dir of the project. And I need to change "Agent" in the string ```from pommerman.agents import RandomAgent, PlayerAgent, Agent```  to BaseAgent (I think, but I'm not sure).
And I found this:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-5-c70a852a2219> in <module>()
      1 # Seed and reset the environment
      2 env.seed(0)
----> 3 obs = env.reset()
      4 
      5 # Run the random agents until we're done

/media/leo/home/playground/pommerman/envs/v0.py in reset(self)
    132         assert(self._agents is not None)
    133 
--> 134         if self._init_game_state is not None:
    135             self.set_json_info()
    136         else:

AttributeError: 'Pomme' object has no attribute '_init_game_state'
``` In the next cells.

**Comment by activatedgeek** [comment]
You are right! This has been fixed in the PR. Thank you for noticing that.

**Comment by cinjon** [comment]
Thanks all for handling this. Closing now.

**Comment by fatemefathi** [comment]
hi 
how can i import pommerman  in pycharm
