### ISSUE TITLE
Fails to run with pyglet 1.3

### ISSUE THREAD

**Issue by bgalbraith** [MultiAgentLearning/playground#43]
Trying to run the environment with a fresh conda install produces the following error when you try to run the environment loop in the notebook: 
NotImplementedError: abstract

This appears to be an issue with OpenAI gym and some breaking change in pyglet 1.3. See: https://github.com/openai/gym/issues/775/. Downgrading to pyglet 1.2.4 solves the issue.

**Comment by cinjon** [comment]
@bgalbraith are you seeing this error in the notebook only?

**Comment by bgalbraith** [comment]
@cinjon I tried it again from a clean conda env and ran the initial demo code from the notebook in the python shell. It appeared to work fine, so this seems to be restricted to running from within the notebook.
