### ISSUE TITLE
Manual user control example in notebook fails due to missing method

### ISSUE THREAD

**Issue by bgalbraith** [MultiAgentLearning/playground#44]
this line:
`on_key_press, on_key_release = utility.get_key_control("arrows")`
results in the following error:
`AttributeError: module 'pommerman.utility' has no attribute 'get_key_control'`

**Comment by activatedgeek** [comment]
Thanks for notifying! This has been fixed in #40.

**Comment by lucasb-eyer** [comment]
#40 doesn't touch the notebook in the diff?  This error is my fault because I forgot to adapt the notebook in #39, I'll fix it shortly.
