### ISSUE TITLE
Agent using Forward Model in Utility Function

### ISSUE THREAD

**Issue by LuvneeshM** [MultiAgentLearning/playground#50]
The agent does not have access to some of the parameters that have to passed into the forward model's run method. For example the agent does not have full access to the flames object, even when reconstructing the flames object using its observation. 

Also when using the run method, it calls the act method for agent passed. Therefore it will call the act for our agent whose act method calls the run method in the forward model, leading to an infinite loop.

**Comment by cinjon** [comment]
So I know I understand, do you just want to be able to do a deepcopy of a current ForwardModel in order to yield those objects?

Also, do you mind breaking out the 2nd thing into another issue and including an example? Thanks.

**Comment by LuvneeshM** [comment]
Yeah, I am pretty sure that would work.

**Comment by cinjon** [comment]
This issue stagnated and I realized that this can be accomplished via the observations passed into `def act` in the base_agent class. You can use that to create a forward model off of what's currently on the board. 

Consequently closing this. Let me know if there's an issue with my prescribed solution.
