### ISSUE TITLE
Callback to Agent about episode end.

### ISSUE THREAD

**Issue by cinjon** [MultiAgentLearning/playground#52]
An end-of-episode signal to the agent would be beneficial. This could help unify inference (run_battle) with training. It could also help with MCTS and alerting it to reset the search tree.

In BaseAgent, this could look like:

def episode_end(reward):
  """Fill in here"""
  pass

**Comment by cinjon** [comment]
@tambetm, aye?

**Comment by tambetm** [comment]
I'll give it a shot ASAP. I still have to catch up with the latest commits in master :).

**Comment by tambetm** [comment]
I'll give it a shot ASAP. I still have to catch up with the latest commits in master :).

**Comment by cinjon** [comment]
Merging this into #63 as it's more active.
