### ISSUE TITLE
Forward Model calls agent's act method

### ISSUE THREAD

**Issue by LuvneeshM** [MultiAgentLearning/playground#53]
When using the run method from the forward model in utility.py, it calls the act method of the forward model. This act method then calls the act method for each agent passed. 

Take for example, if this run method was originally called from the agent's act method (for example if we called it from Simple agent's act method), then we would call the act method for our agent again. This would lead into an infinite loop as calling the agent's act method would call the run method from the forward model, which would call the act method from the forward model, which would call the act method of the agent again.

**Comment by cinjon** [comment]
Can you please include a minimal example? I can see that this would happen, but I have not had this happen before and would like to see what you're doing that caused it.

**Comment by cinjon** [comment]
Closing this. Lmk if you can reproduce.
