### ISSUE TITLE
About v0/v1/v2

### ISSUE THREAD

**Issue by lucasb-eyer** [MultiAgentLearning/playground#56]
I haven't read the implementation extensively yet so apologies if it would be obvious, but it feels wrong to have these as separate "versions" of the game. Currently, there is no "radio+collapse" mode for example, and with the upcoming sudden-death (v3), there are even more meaningful combinations which are missing.

So really, these modes feel more like individual, orthogonal options: collapsing walls or not (v0 vs. v1), communication or not (v0,v1 vs. v2) and sudden-death or not (v0,v1,v2 vs. v3). Any combination of these three binary options seems to make sense to me. Is there a reason for the way it currently is, that I'm missing? Or is it correct, but simply not a priority/not important right now?

**Comment by cinjon** [comment]
I agree that they are mostly orthogonal (the collapsing walls and sudden death are, although communication is not as much). 

A reason for the current setup ("Versions") is that it makes it easy to handle environmental changes, especially community contributed ones. Another reason is that it's a holdover from how I've previously iterated on models :). Two other possible setups are:
1. "Kwargs": Use kwargs liberally.
2. "Wrappers": Use environment wrappers a la Gym's setup.

I greatly prefer "Versions" to "kwargs" as the latter would become very unwieldy. 

Arguably, "Wrappers" is just as good as (if not better than) the status quo. In that scenario, we could keep the versions as a collection of wrappers and then have the config still call a "v#". Alternatively, we could have the config directly call the wrappers.

One observation though about the current setup is that it may just be named poorly. If we instead called them more aptly ("_CollapsingWallsEnv", "_CheapTalkEnv", ...), then we could use multiple inheritance in a "CollapsingCheapTalkFFAGame" and probably satisfy these concerns.

Thoughts? Did you have another possible setup in mind?

**Comment by cinjon** [comment]
Although actually ... the multiple inheritance idea probably wouldn't be sufficient.

**Comment by lucasb-eyer** [comment]
I don't have any good proposals yet :smile: hence just asking about it to see the reasoning. For one, I now see that it's not that simple/obvious with the communication one.

I agree the MI would not be enough and, even though I'm a huge fan of (ab)using `kwargs` in my own code, I agree that it is not the best idea here.

Maybe it's not a problem (yet) as the modes are few. If it does become a problem for me, I'll look into it deeper. Feel free to close the issue since it's not really actionable yet, or leave open for discussion.

**Comment by cinjon** [comment]
As much as I'd like to make this true, I don't have the cycles and it's not a priority for others. If anyone really wants to make this change, I will accept a PR. 

Otherwise, closing for now.
