### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by cinjon** [MultiAgentLearning/playground#60]
Include style considerations in the CONTRIBUTING.md and a linter (pylint) in the dir.

**Comment by weseldridge** [comment]
Yeah, I like that. There is one for setuptools.

https://github.com/johnnoone/setuptools-pylint

It lets you do...

```
python setup.py lint
```

**Comment by weseldridge** [comment]
The code has all been updated to pass linting now.

I need to update the docs and update the travis config. Do we want travis to fail if the PR doesn't pass linting?

**Comment by cinjon** [comment]
Yeh, we don't want that to not be effective going forward. It seems that the error is in the linter:

https://travis-ci.org/MultiAgentLearning/playground/builds/408168167
File "/home/travis/build/MultiAgentLearning/playground/pommerman/agents/player_agent.py", line 77
IndentationError: unexpected indent

**Comment by cinjon** [comment]
Done via #117
