### ISSUE TITLE
Providing terminal state information along with observation to BaseAgent's act method.

### ISSUE THREAD

**Issue by Rishav1** [MultiAgentLearning/playground#63]
For designing recurrent RL models, the information about when the episode has ended (in order to reset LSTM layers' hidden states) is necessary, even during evaluation. So current terminal flag information along with observed state should be provided in BaseAgent's act abstract function.

**Comment by cinjon** [comment]
Thanks, is this the same as #52 or are you thinking that you need more?

**Comment by Rishav1** [comment]
Sure, end signal can be implemented as a separate function also. But I don't see the point of sending a reward feedback along with it. Would it be the reward for terminal state or the entire accumulated episode reward? Also, isn't leaving out reward feedback in the agent interface important to enforce static agents while evaluation via DockerAgentRunner? Otherwise while evaluation, agents will be able to utilize rewards for improvement. 

In my opinion, adding a boolean terminal parameter in BaseAgent act() like the following should suffice.

def act(self, obs, terminal, action_space):
    raise NotImplementedError()

**Comment by cinjon** [comment]
Right, so #52 was saying "tell me when the episode has ended" and it's only called (per agent) with the final reward, not all of them.

@tambetm , do you think it would satisfy your needs to include this in the act instead of having a separate callback?

**Comment by tambetm** [comment]
I thought of this, but firstly reward is provided only in the episode end, secondly the episode ends _after_ you have taken the action, so in final call to act() with terminal=True there is no intention of making use of the returned action (actually you could return None in that case). I think having separate callback would be more clear design.

Haven't had much time to work on Pommerman this week, but I plan to take a look today.

PS. Current reward scheme is unsuitable for self-play - if everybody just stays put, they will all get reward 1 in the end. It seems to me that for training one would need to implement custom reward scheme.

**Comment by cinjon** [comment]
Re reward scheme being unsuitable, I agree, that's something that we've realized as well and just haven't changed yet. Current thought is that everyone gets -1 if the game goes to the end.

**Comment by Rishav1** [comment]
Right, @tambetm is right, given current rewarding scheme, a callback with episode reward would be a better design. 

@cinjon, are you planning on changing the reward scheme from episodic to per step, (for instance rewarding collection of powerups and killing enemies)?

If so, then the reward would have to be shifted from episode_end callback to act callback.

**Comment by cinjon** [comment]
We're not going to change the official scheme like that. The idea of the game is that you are rewarded for winning a la how other games are perceived (Go, Chess, etc). 

There will always be other modes, such as "Make the game fun for the other player" which will want other reward functions, and there will of course be other ways of training agents that will benefit from having the reward be dense. We also won't prejudice against submissions to the competitions that use dense rewards. The value in having it be a single sparse reward is that there's a clear goal and setup for future posterity.

**Comment by cinjon** [comment]
@tambetm , @Rishav1 , please check out #64.

**Comment by tambetm** [comment]
The PR looks good, but I'm not sure rewarding everybody with -1 at max_steps fixes the problem. Basically it makes lasting till the end of episode equivalent to blowing yourself up with a bomb. But I don't think it matters. Rewards are only used during training, so it's up to you to come up with reward scheme that hopefully works also in the final battle. I think the rewarding scheme is going to be one of the key differentiators between competitors.

**Comment by cinjon** [comment]
Thanks for taking a look. I'll push out the PR and close this issue. 

(It's important in that it's recognized for posterity as being a non-positive outcome. I do agree though that if you just sit around for 2500 steps, then your gamma weighted -1 is quite small.)
