### ISSUE TITLE
Better Pommerman graphics

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#7]
I notice in the "How can I help?" section there is a topic of better graphics. I agree fully. This morning I started working on a sprite sheet. I am assuming to start we need sprits for each of the Item in the Item Enum Class?

I have started looking over the code that builds the board. It will need to be modified to support sprites. I haven't gotten into the implementation yet.

I will post the sprite sheet once I have a first decent copy of it.

**Comment by cinjon** [comment]
Cool, that would be awesome! Would gladly appreciate any help along this direction.

**Comment by weseldridge** [comment]
![artboard 1](https://user-images.githubusercontent.com/138982/36748544-bdc6acd4-1bbd-11e8-8078-1143210375d1.png)

I am still working on the pommerman agents. Do you think this is getting closer?

**Comment by cinjon** [comment]
I really like how this is coming along. A couple thoughts:
1. Can we change the shading on 7 (+ bomb) to be more different from 10 (skull)? I love that the other items are colored.
2. Does it make sense to have the flames be more expansive and consequently look like it's the whole block?

**Comment by weseldridge** [comment]
I went back to the gold for the bomb coin. I can try another color if you would like to see the coin in a different color(s).

![screen shot 2018-02-27 at 15 41 50 pm](https://user-images.githubusercontent.com/138982/36756516-d59c5d7e-1bd4-11e8-8279-109f8aeaf39c.png)

I would really like to do something like this for the flames. However, the game runtime doesn't support it right now.

![nes - bomberman - general sprites](https://user-images.githubusercontent.com/138982/36756565-fed37bb4-1bd4-11e8-90c4-0dd135e8fcc5.png)

I am not native to Python and do not know the libraries that the runtime use. I thought maybe in a future release we can have really good flames.

After saying all of that, I will create a couple more fire/explosion examples to see which works best.

**Comment by cinjon** [comment]
Ahh, I see what you mean. I agree that that would be nice to add, but I think we're both bandwidth constrained and would rather make agents :). Let's stay away from that complexity for now.

Sg! Thanks again for doing this. It's going to make it a lot better.

**Comment by weseldridge** [comment]
![titles](https://user-images.githubusercontent.com/138982/36867650-5f3b3f78-1d5b-11e8-9336-6a270a215dd2.png)

Here is what I came up with for the agents. What are your thoughts? Sorry about them being all messed up. It is how they were exported...

**Comment by weseldridge** [comment]
Ok. I moved all the stuff from PS to illustrator. Still, need to redo the wood, but here is what I could do this afternoon. Getting closer!!

![sprites](https://user-images.githubusercontent.com/138982/36871869-2a069b32-1d69-11e8-800e-37e9041be4f6.png)

**Comment by cinjon** [comment]
!!! This is awesome. 
Have you tried changing the graphics to be these gorgeous sprites? I haven't yet thought through the proper way to do that.

**Comment by weseldridge** [comment]
I haven't yet. I am going to start that tomorrow and over the weekend. It will push some changes and get some feed back.

**Comment by weseldridge** [comment]
This is the start of the graphics update.

https://github.com/weseldridge/playground/commit/358cb4120d7064be7397c05f53466dfc49a305b3

**Comment by weseldridge** [comment]
I finished the wood tile and updated the dummy tile. Also worked on a couple of suggestions from the PR. A few more updates are still needed. 

https://github.com/weseldridge/playground/blob/17127b6b8405a645c96e108c25cd74b4956c77b0/pommerman/envs/images/Sprites-03.png

https://github.com/weseldridge/playground/blob/17127b6b8405a645c96e108c25cd74b4956c77b0/pommerman/envs/images/Sprites-14.png

<img width="650" alt="screen shot 2018-04-05 at 5 56 53 pm" src="https://user-images.githubusercontent.com/138982/38395958-19b70a66-38fb-11e8-9415-25561a2548e0.png">
<img width="651" alt="screen shot 2018-04-05 at 5 57 06 pm" src="https://user-images.githubusercontent.com/138982/38395961-1bb307c0-38fb-11e8-856c-49f6352a582e.png">

**Comment by cinjon** [comment]
👍 !
It'd be nice to see them on the board, but from this vantage point, yes they do look more distinguished. 

1. Is the gray one the dummy?
2. Is the bottom right one just there to show what it used to be?
3. If it's still an issue when they're on the board, three possibilities:
  a. Color their mouth the color of their helmet
  b. A nose that's the color of their helmet.
  c. Expand the size of the colored part of their helmet by making the sides a little thinner to give room for bigger ear muffs.

**Comment by weseldridge** [comment]
The gray one is the dummy. The bottom right is b/c I am a lazy cropper. 😬 

I am doing some db training stuff today. I will post the updated board in a bit. 👌

**Comment by weseldridge** [comment]
The top image is with the updated agents. The bottom one is for reference.

![screen shot 2018-04-10 at 09 49 02 am](https://user-images.githubusercontent.com/138982/38564314-8341aeb2-3ca4-11e8-81f5-05df808fbbcf.png)

<img width="864" alt="38442490-173f4420-39ae-11e8-818c-3b3577a3b222" src="https://user-images.githubusercontent.com/138982/38564364-9a09279c-3ca4-11e8-8d2b-d483b088022f.png">
