### ISSUE TITLE
Simple Agent stop moving/acting

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#70]
I have noticed a few times the simple agent stop during play. There have been a few times they make a few moves then stop. If one of the agents keep moving and breaks into another agent's starting area the stopped agent will start moving again.

**Comment by cinjon** [comment]
Yes, I've seen this a bunch too. It hasn't been a priority for me to solve because I think it would just make the agent stronger. I'd rather have the community make a different agent that's better than change this one now.
