### ISSUE TITLE
Single json file per game/episode

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#72]
As I have started playing with being able to do a replay of a game I have noticed that each step in a game is saved out to a single file. 

Would it make more sense for each game/episode to have its own file? It would help if you wanted to record each episode for some reason. It would also help with being able to play back games once that is added to the website.

**Comment by cinjon** [comment]
Are you thinking it would be a concatenation of the current one into one big json instead of a folder of smaller ones?

**Comment by weseldridge** [comment]
I think there is a couple of ways we can do it. It would be nice to have something that is performant. If for some reason you wanted to do it for some large n episodes I would hate to add any amount of measurable time to it. The compounding of that would be god awful.

A few ideas
- concatenating all of the files.
- encoding the data in json then just appending the encoded data to the file. Then at the end of the episode add the begging and ending json formatting pieces.
- keeping all of the data in memory then building the file at the end. This could take up a lot of memory though... If it fails in the middle you also lose all of that data.

It might also be good to include some metadata about the episode. Agent types, winner, etc.

I mentioned in the past how halite uses a binary formate. This would help save space. It is not really human accessible though.

**Comment by weseldridge** [comment]
@cinjon and @staynalive what do you think the best approach is?

**Comment by cinjon** [comment]
Seems like we could get away with saving all of these preliminary states to disk and then, post game or atexit, building a single json file repping the complete game that is just a concatenation of the others. 

That seems like the easiest approach. Are there any concerns with it?

**Comment by weseldridge** [comment]
Nope. That works for me.

**Comment by weseldridge** [comment]
I also notice that the only way to save or tell the env to save json is to pass it in via the render method on the env. Should I also add a `set_record_json_dir` on the env for recording game state on the server? Maybe change that interface altogether and remove it from the render method.

**Comment by cinjon** [comment]
Yes! That makes a lot of sense. Good idea.

**Comment by cinjon** [comment]
This was completed! Thanks Wes.
