### ISSUE TITLE
 Two actors on adjacent squares can switch positions

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#76]
Two actors on adjacent squares can walk through each other and switch positions:

From:
![screenshot from 2018-05-08 17-22-32](https://user-images.githubusercontent.com/2333473/39828483-686347f0-5378-11e8-9c56-69af5f3d199d.png)
To:
![screenshot from 2018-05-08 17-22-56](https://user-images.githubusercontent.com/2333473/39828484-687cf4de-5378-11e8-82ff-5ccfa1c912bc.png)

**Comment by cinjon** [comment]
Thanks for this report. I'll look into it. In the meantime, can you give any more info as to what happened in the game. Were they both simple agents?

**Comment by suphoff** [comment]
I am just trying to understand the rules of the game in detail by reading through ForwardModel.step.
To verify my understanding of the code I started a game with  two RandomAgents and two PlayerAgents.
Once the RandomAgents killed themselves I drove both PlayerAgents to verify manually that they can indeed switch positions.

**Comment by suphoff** [comment]
Yes - both agents need to move to the other agent's position at the same step

**Comment by cinjon** [comment]
Thanks so much for submitting this. I addressed it in this commit --> https://github.com/MultiAgentLearning/playground/commit/abad150bf43022df1712f63d32a986aa851e4fa2. Closing this for now, but please let me know if you find a scenario where this isn't sufficient.
