### ISSUE TITLE
Bomb moves off board

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#82]
Bomb positions on moving bombs can become negative - appearing on the other side of the board.
Bomb positions on moving bombs can also become bigger than the size of the board - causing index errors.

**Comment by cinjon** [comment]
Thanks for catching that. I just pushed a commit that addresses this --> https://github.com/MultiAgentLearning/playground/commit/071e83c1fd8ec8e31cdb7ea0b2dee569246ca04e
