### ISSUE TITLE
python train_with_tensorforce.py & run_battle.py call failing

### ISSUE THREAD

**Issue by dhaw92** [MultiAgentLearning/playground#83]
I tried to train the tensorforce agent using the following command 
`
python train_with_tensorforce.py agents=tensorforce::ppo,test::agents.SimpleAgent,test::agents.SimpleAgent,test::agents.SimpleAgent 
 --config=PommeFFA-v0
` mentionned [here](https://github.com/MultiAgentLearning/playground/blob/master/pommerman/cli/train_with_tensorforce.py#L8) but I get the following error:

```
Traceback (most recent call last):
  File "pommerman/cli/train_with_tensorforce.py", line 22, in <module>
    from .. import helpers, make
ValueError: attempted relative import beyond top-level package
```

I was trying to find a way to be able to modify the training script and run it but this way didn't work, I found a workaround but I wanted to point out this issue since it's in the docs & not working.
If I am missing something to run the command please let me know.
The same problem with `python run_battle.py` too.

**Comment by cinjon** [comment]
Can you try using ```pom_tf_battle``` instead? Does it still report that?

**Comment by dhaw92** [comment]
It works fine using `pom_tf_battle` but doesn't give me what I want, which is to modify train_with_tensorforce.py and run it e.g. I want to train the agent for more episodes.

**Comment by cinjon** [comment]
Hey, sorry for the lack of update. I noticed you said you found a workaround; what was it?

**Comment by dhaw92** [comment]
I created a file under repository's root folder with the following code that I copied from the original pom_tf_battle that was installed under `/home/$USER/anaconda3/bin/pom_tf_battle` :
```
import re
import sys

from pommerman.cli.train_with_tensorforce import main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(main())

```
This way I could run the modified train_with_tensorforce.py file.

**Comment by b-kartal** [comment]
python run_battle.py also works if you explicitly define imports as follows:

from pommerman import helpers, make
from pommerman.agents import TensorForceAgent
