### ISSUE TITLE
Bomb movement restriction checks rely on outdated information

### ISSUE THREAD

**Issue by suphoff** [MultiAgentLearning/playground#84]
( Pulling item 2 of #77 into this issue as requested by @cinjon and adding examples )

Bomb movement restriction checks rely on the last state of the board with only fire and newly revealed items updated. This causes various issues (a few examples below).

Happy to contribute to fix the issue - however as changes are non-trivial it may be beneficial to fully specify {moving} agent/ moving} bomb/ explosion/ fire interaction first before starting work on this issue.

---
Examples:

Item Symbol | Explanation
-|-
:panda_face: | Agent 0
:fox_face: | Agent 1
:bomb: | bomb

Item Attribute | Explanation
-|-
:arrow_down: :arrow_up: :arrow_left: :arrow_right:| Action for Actors or direction for moving bomb
:soccer: | Agent can kick

---
**Example 1:**

X|0|1|2|3
-|-|-|-|-
**0**| :panda_face: :arrow_right: :soccer:  |:bomb:| | :fox_face: :arrow_left: 

Next step should be either:

X|0|1|2|3
-|-|-|-|-
**0**| :panda_face: :soccer:  |:bomb:| | :fox_face: 

or maybe

X|0|1|2|3
-|-|-|-|-
**0**| :panda_face: :soccer:  |:bomb:|  :fox_face: |

but actually is

X|0|1|2|3
-|-|-|-|-
**0**| |:panda_face: :soccer:  |:bomb: :arrow_right:   :fox_face: |

---
**Example 2:**

X|0|1
-|-|-
**0**| :bomb: :arrow_right:  | 
**1**| |:bomb: :arrow_up:  

next step should be:

X|0|1
-|-|-
**0**| :bomb:  | 
**1**| |:bomb:

but actually is:

X|0|1
-|-|-
**0**| |:bomb: :bomb:
**1**| |

---
**Example 3:**

X|0|1|2|3
-|-|-|-|-
**0**| :panda_face: :arrow_right: :soccer:  |:bomb:| :fox_face: :arrow_right: |

Next step should probably be

X|0|1|2|3
-|-|-|-|-
**0**| |:panda_face: :soccer:  |:bomb: :arrow_right:|  :fox_face: 

but is

X|0|1|2|3
-|-|-|-|-
**0**| :panda_face: :soccer:  |:bomb:| | :fox_face:

**Comment by cinjon** [comment]
🥇 

Let's fix this. I hear that changes would definitely benefit from making this logic more clearly delineating, however do you think that we couldn't accomplish this in the given framework still?

**Comment by suphoff** [comment]
Should be just a major rototilling of the step function.
However I highly recommend fully specifying the desired behavior first.

---
 @weseldridge talked about a web app to manually create start states.
If that app could be enhanced to create any state (including flames, lifetimes, movement) and optional agent actions, it would be a great tool to document intended behavior and as test and verification data for the step function. (State x Actions -> State, Well except the :skull: as it is non deterministic :frowning_face: - but we could fix this by splitting :skull: into three different :skull: types and just unify them to a single :skull: type in observation )

**Comment by weseldridge** [comment]
I am hoping to get the first rough version of this out today or tomorrow. I will share it here and in discord. PRs are welcome to get it where everyone wants its.

**Comment by cinjon** [comment]
This was addressed in a recently merged branch. Thanks @suphoff !
