### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by weseldridge** [MultiAgentLearning/playground#9]
A starting guide to help people find helpful research and how to start building an agent.

**Comment by weseldridge** [comment]
I added a getting started guide markdown page. It is a lazy start having only links to research papers @cinjon posted in discord.

**Comment by cinjon** [comment]
nice addition. quick edit: the first name is off. i think it should be PPO. can you change that please? i'll add more color to this after we rebase it.

**Comment by weseldridge** [comment]
Cool. Done!
